### PR TITLE
Spudfile: first draft

### PR DESCRIPTION
**Pull request by eentzel**
@CharlieSu @riltsken @AMeng no particular rush but see if this looks sane. This service does nothing yet, but will be the API powering the new dev portal. I'm happy to take a stab at setting up things in Asgard if you like, or let you guys do it.

### CODE REVIEW

**Comment by eentzel** [comment]
ping @CharlieSu — OK for me to go ahead with Asgard setup (in staging)?

**Comment by riltsken** [comment]
Maybe @CharlieSu knows more about this project, but would like some background before :+1: Also if this is a new project it might be easier to leave off the production from the spudfile as I don't know the access patterns expected for production (eg, what are the right security groups). Maybe this has all been discussed before and you can ignore me :)

**Comment by eentzel** [comment]
What, more than my 1line README? ;) This is the backend for API key signup / management & our customer-facing portal. It will gradually take over those duties from the ever-popular github.com/fullcontact/fullcontact-api

**Comment by CharlieSu** [comment]
Spudfile looks fine, but yeah, I'd like to know more about what this is and
have more of a heads up when we're brining on new services so that I can
understand the cost implications.

On Fri, May 8, 2015 at 10:20 AM, Samuel Toriel <notifications@github.com>
wrote:

> Maybe @CharlieSu <https://github.com/CharlieSu> knows more about this
> project, but would like some background before [image: :+1:] Also if this
> is a new project it might be easier to leave off the production from the
> spudfile as I don't know the access patterns expected for production (eg,
> what are the right security groups). Maybe this has all been discussed
> before and you can ignore me :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcontact/glados/pull/1#issuecomment-100285563>.
>



-- 
Charles Sullivan
DevOps Manager
FullContact | fullcontact.com
m: 720.397.1492
Skype: charlie.sullivan

**Comment by eentzel** [comment]
@CharlieSu https://www.pivotaltracker.com/epic/show/1782178 is the Pivotal epic. Cost-wise all I want for now is an m1.small in staging.

**Comment by CharlieSu** [comment]
LGTM.  If resource utilization is going to change in the future please let
us know.

On Fri, May 8, 2015 at 10:31 AM, Eric Entzel <notifications@github.com>
wrote:

> @CharlieSu <https://github.com/CharlieSu>
> https://www.pivotaltracker.com/epic/show/1782178 is the Pivotal epic.
> Cost-wise all I want for now is an m1.small in staging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fullcontact/glados/pull/1#issuecomment-100287851>.
>



-- 
Charles Sullivan
DevOps Manager
FullContact | fullcontact.com
m: 720.397.1492
Skype: charlie.sullivan

**Pull request merged**
